apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  namespace: vprofile
  labels: 
    app: vproapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
      - name: vproapp
        # image: {{ .Values.appimage}}
        image: yemisiomonijo/vprofileapp:V67
        ports:
        - name: vproapp-port
          containerPort: 8080
        resources:
          limits:
            cpu: 1
            memory: 700Mi
          requests:
            cpu: 500m
            memory: 600Mi
      initContainers:
      - name: init-mydb
        image: busybox
        command: ['sh', '-c', 'until nslookup vprodb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;']
      - name: init-memcache
        image: busybox
        command: ['sh', '-c', 'until nslookup vprocache01.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;']
